# 기본 플랫폼을 android로 설정
default_platform(:android)

platform :android do
  # dotenv 플러그인을 사용하지 않고 .env 파일을 로드하는 코드 추가
  require 'dotenv'
  Dotenv.load('.env')  # .env 파일 자동 로드

  desc "🚀 Internal Test용 업로드"
  lane :internal do
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )

    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "internal",
      aab: "./app/build/outputs/bundle/release/app-release.aab",
      json_key: ENV["PLAY_STORE_JSON_KEY"], # ⬅️ 환경변수에서 키 경로 참조
      skip_upload_apk: true
    )
  end

  desc "🚀 Production 업로드"
  lane :production do
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )

    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "production",
      aab: "./app/build/outputs/bundle/release/app-release.aab",
      json_key: ENV["PLAY_STORE_JSON_KEY"], # ⬅️ 환경변수에서 키 경로 참조
      skip_upload_apk: true
    )
  end
end
